name: WAH30
favicon: null
layout_spectrum: 0.98435
typography_spectrum: 0.55748
title: Werewolves at Hour 30
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1b2121'
    - '#ffeff9'
    - '#c1cdc9'
    - '#687673'
    - '#92a5a1'
  brandStrength: 0.5
  lightness: 0.5625
  saturation: 0.75
  rhythmicContrast: 0.5
purpose: []
