title: Werewolves at Hour 30
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.1875
  brandStrength: 0
  lightness: 0.125
  brandColors:
    - '#ffffff'
    - '#101314'
    - '#3a4547'
    - '#810000'
    - '#84989b'
  rhythmicContrast: 0.5
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
name: WAH30
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.55748
layout_spectrum: 1
