name: WAH30
favicon: null
layout_spectrum: 0.94307
typography_spectrum: 0.55748
title: Werewolves at Hour 30
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1e1e1e'
    - '#dddddd'
    - '#424242'
    - '#707070'
    - '#a3a3a3'
  brandStrength: 0.294509282335639
  lightness: 0.8568086680024862
  saturation: 0.11766651412472129
  rhythmicContrast: 0.6549387185368687
purpose: []
