name: WAH30
favicon: null
layout_spectrum: 0.98435
typography_spectrum: 0.55748
title: Werewolves at Hour 30
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#787878'
    - '#a6a6a6'
    - '#d3d3d3'
  brandStrength: 0.0625
  lightness: 0.125
  saturation: 0.1875
  rhythmicContrast: 0.5
purpose: []
